steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "JWT Auth: resgate da chave publica"
    entrypoint: "bash"
    args: [ '-c', 'gcloud secrets versions access latest --secret=sigoms_users_public_pem  > public.pem' ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "JWT Auth: resgate da chave privada"
    entrypoint: "bash"
    args: [ '-c', 'gcloud secrets versions access latest --secret=sigoms_users_private_pem  > private.pem' ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/sigoms-users:$SHORT_SHA"
      - "--build-arg"
      - "APP_ENV=${_APP_ENV}"
      - "--build-arg"
      - "APP_SECRET=${_APP_SECRET}"
      - "--build-arg"
      - "DATABASE_URL=${_DATABASE_URL}"
      - "--build-arg"
      - "JWT_SECRET_KEY=${_JWT_SECRET_KEY}"
      - "--build-arg"
      - "JWT_PUBLIC_KEY=${_JWT_PUBLIC_KEY}"
      - "--build-arg"
      - "JWT_PASSPHRASE=${_JWT_PASSPHRASE}"
      - "--build-arg"
      - "CORS_ALLOW_ORIGIN=${_CORS_ALLOW_ORIGIN}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "Push"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/sigoms-users:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy"
    args:
      - "run"
      - "deploy"
      - "sigoms-users"
      - "--image"
      - "gcr.io/$PROJECT_ID/sigoms-users:$SHORT_SHA"
      - "--platform"
      - "gke"
      - "--cluster"
      - "cluster-puc"
      - "--cluster-location"
      - "us-east1-b"
      - "--port"
      - "80"
      - "--namespace"
      - "sigoms-users-puc"
      - "--min-instances"
      - "1"
